matrix-org/pantalaimon

pantalaimon/panctl.py
Version 3.0 has a few [backward-incompatible changes](https://github.com/prompt-toolkit/python-prompt-toolkit/blob/0b2221779e737a6c777efe3b8b466c021e197093/docs/pages/upgrading/3.0.rst) which this prepares for.
=> Prepare for prompt-toolkit 3.0

setup.py
=> [setup.py] prompt_toolkit depency requires version 2.x

pantalaimon/client.py
Event callbacks are only called for events that come through a sync resposne. Since events in the scrollback might be decryptable there's no reason to not store the media info for those as well.
This closes: https://github.com/matrix-org/pantalaimon/issues/61.
=> client: Store media info when decrypting instead of using a event callback.

tests/conftest.py
Many systems don't have a keyring configured for DBus by default, which
requires extra setup in order to run the proxy tests successfully.
=> tests: Don't use keyring during tests

CHANGELOG.md, pantalaimon/daemon.py
The plan for encrypted bridges is for them to authenticate using access tokens rather than a password, which means that when Pan attempts to login with a provided password, it falls over. I'm not terribly happy with this solution, but it's does make things work again.
=> Do not try to login if the user authenticated via other means

docs/man/pantalaimon.5, docs/man/pantalaimon.5.md
The homeserver URL used in the description did not match the one in the example config
=> Use correct homeserver URL in example description

pantalaimon/daemon.py
Pan will throw a KeyError if msgtype is not defined, however events can omit the msgtype in some cases. In any case, it should be up to the homeserver to validate this key rather than pan.
=> Do not fail if msgtype is not defined

setup.py
According to the [changelog](https://github.com/poljar/matrix-nio/blob/0.17.0/CHANGELOG.md#0170---2021-03-01), there are no breaking changes.
=> setup.py: Bump the allowed nio version

pantalaimon/daemon.py, pantalaimon/store.py, setup.py
If a client supplies a thumbnail when sending some media into a room, pantalaimon does not currently add the information to decrypt the thumbnail to the outgoing message - meaning that the thumbnail is not displayed.
This fixes that problem by adding the thumbnail_file key in the same way that the file key is added to the outgoing message.
I wasn't sure of the most sensible way to do this (I'm not very familiar with pantalaimon's codebase), but the method I've used seems to work for me! However it's quite possible I've missed or misunderstood something.
=> Encrypt thumbnails uploaded by a client.

pantalaimon/client.py
As discussed recently on the pantalaimon matrix room, these changes should fix `KeyError`s stemming from the homeserver sending a differently structured sync data without rooms such as
```
{'next_batch': xxx_xxx_xxx_xxx_xxx_xxx_xxx_xxx_xxx', 'device_lists': {'changed': ['x']}, 'device_one_time_keys_count': {'signed_curve25519': x}}
```
Patch by @poljar
=> Patch KeyError on sync

pantalaimon/client.py, pantalaimon/daemon.py
Pantalaimon depends on the room state to be present to decide correctly if a message should be encrypted or now. The room state is fetched from the server every time we restart, this means that failure to fetch room states from the server would hinder us from doing the correct decision.
This patch prevents a downgrade to sending unencrypted messages if we're unable to sync at least once with the server.
=> Prevent downgrade on failed sync

pantalaimon/daemon.py
If the original path had quoted slash characters (`%2F`), the code
decoded them and then left them unquoted, causing the forwarded request
to fail.
An example is trying to ban a user with a slash in their name using
Mjolnir, which PUTs a state event with `rule:<username>` in the URL.
Use the undecoded path to avoid this.
=> pantalaimon: Forward raw path instead of quoting the decoded path

pantalaimon/daemon.py
thumbnail_url can be None
when finally passed down to `_get_upload_and_media_info`, https://github.com/matrix-org/pantalaimon/blob/master/pantalaimon/daemon.py#L847 will raiase a `TypeError` since in this case `urlparse` returns `netloc` as bytes instead of string
=> thumbnail_url can be None

pantalaimon/daemon.py
=> fix(daemon): Don't use strip to filter Bearer from auth header

README.md
Handier for those not interested in the code, but just wanting to run the software (or some previous version).
=> Readme: add alternate, quicker Docker build method

README.md
This came up in #matrix-admins-edu-german:matrix.org recently.
1. It is not entirely clear which "user" is meant here, it might mean the matrix user or OS user, both of which are correct but I believe the emphasis here is supposed to be on the OS user. I am not sure how to improve wording in that regard.
2. "Your own user" was interpreted as "its own user", i.e. having a system user for all pantalaimon instances. I believe that is specifically what is **not** intended here. Rather pantalaimon is supposed to be run the same as the app it is proxing, e.g. if using mjolnir, then pantalaimon should also be run by the mjolnir user; if run with element, then it should also be run from that same personal account. I hope that part is more clear with this PR.
=> clarify wording in README#Usage

pantalaimon/daemon.py
The download method of the client was used incorrectly. Fixes #141
=> Fix media proxying

README.md
This is mentioned in #154 and I figured it was probably a good idea to get this in the official README. All credit goes to 
@Arnavion
=> chore: Update README with new setup instructions

pantalaimon/panctl.py, pantalaimon/ui.py, setup.py
Closes #162 by getting rid of `pydbus` in favor of `dasbus`.
=> chore: Remove depreciated dependency pydbus for dasbus

setup.py
Just upgrading the `matrix-nio` package and fixing the version number of `das-bus`.
=> chore: upgrade matrix-nio and fix dasbus version

pantalaimon/daemon.py, pantalaimon/main.py
Suppose that Alice logs in using Element. Before this change, when Bob would send a DM to Alice through Pantalaimon, Alice would not be able to decrypt Bob's initial message. Instead, she would see
```
Unable to decrypt: The sender's device has not sent us the keys for this message.
```
and Pantalaimon's `olmsessions` table would have no associated records. Any future messages would be visible however. On the other hand, when Alice (using Element) is the one to send the first DM to Bob, he can decrypt the initial message.
For Pantalaimon to execute `/keys/claim`, `get_missing_sessions` must return the invitee's device (and log `Missing session for device`). If Pantalaimon calls this method too soon, then `self.device_store` will not have the device. To populate `self.device_store` before …
=> Decrypt initial message after joining new DM

pantalaimon/main.py, setup.py
These have the same interface since platformdirs is just a fork of appdirs so luckily this was as easy and changing the dependency name.
=> chore: change from appdirs to platformdirs

pantalaimon/panctl.py
I have used the  shlex.split function which correctly handles quoted strings, ensuring that the entire passphrase is treated as a single argument.
=> Issue #138: Using shlex.split instead str.split

tests/pan_client_test.py
This fixes the tests by removing an used fixture (`loop`) which also didn't exist. Makes me realize tests should probably be running in the CI. I am now having a bit more time to work on this now that the move has finished and work has settled down a bit. Fixes the last issue with #183 .
=> chore: Fix failing tests by removing unused fixture
